/*
 * Copyright (c) 2021, NVIDIA Corporation. All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:

 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/**
 * @file
 * <b>Specifies structures that define the interface to the SE hardware
 *   random number generator (SE RNG1)</b>
 *
 * @b Description: This file specifies structures used to interface with
 *   the Jetson security engine (SE) hardware implementation of
 *   the NIST-SP 800-108 counter-mode key definition functions (KDFs).
 */

#ifndef __RNG_SRV_H__
#define __RNG_SRV_H__

#include <common.h>
#include <stdint.h>
#include <trusty_ipc.h>

/**
 * @defgroup  random_number_group  Secure Random Number Generator
 *
 * @note  This feature is supported only in
 *   NVIDIA<sup>&reg;</sup> Jetson Xavier&trade; NX,
 *   NVIDIA<sup>&reg;</sup> Jetson AGX Xavier&trade; series, and
 *   NVIDIA<sup>&reg;</sup> Jetson&trade; TX2 series devices.
 *
 * A hardware-based random number generator (RNG) generates true random numbers
 * for use by Trusted Applications (TAs).
 *
 * The RNG is accessed through IPC. For information about its use,
 * see the topic
 * <a href="https://docs.nvidia.com/jetson/l4t/Tegra%20Linux%20Driver%20Package%20Development%20Guide/trusty.html#wwpID0ESHA">
 *   Hardware Random Number Generator Function
 * </a> in <em>Jetson Linux Developer Guide</em>.
 *
 * @ingroup trusty_key_generation_group
 * @{
 */


/** \brief Maximum length of a random number. */
#define RNG_SRV_DATA_SIZE 2048

/**
 * \brief Holds an IPC packet for communication with the RNG.
 */
typedef struct rng_srv_msg {
	uint32_t rng_size;			/**< Actual size of a requested
						 *   random number. */
	uint8_t rng_data[RNG_SRV_DATA_SIZE];	/**< Holds the random number
						 *   generated by RNG. */
} rng_srv_msg_t;

/** @} */

void rng_srv_process_req(iovec_t *ipc_msg);

#endif /* __RNG_SRV_H__ */
