/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-generic32"
#define DATE "built on: Mon Aug 10 12:29:19 2020 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','g','c','c',' ',' ','-',
    'W','a','l','l',' ','-','O','3',' ','-','D','O','P','E','N','S',
    'S','L','_','U','S','E','_','N','O','D','E','L','E','T','E',' ',
    '-','D','N','D','E','B','U','G',' ','-','D','O','P','E','N','S',
    'S','L','_','A','P','I','_','C','O','M','P','A','T','=','0','x',
    '1','0','1','0','0','0','0','0','L','\0'
};
